### ISSUE TITLE
Overlay z-index being set to -1

### ISSUE THREAD

**Issue by lkovaleva** [PolymerElements/iron-overlay-behavior#127]
When a dialog is put into the DOM at the same time as it is opened, the overlay z-index calculation receives "" as the current z-index.
`_getOverlayZ` calculates `var z1 = Number(window.getComputedStyle(overlay).zIndex);` which evaluates to 0 for "" which passes the === check and and hence turns into -1 for the overlay z-index down the line.
This issue can be addressed by changing the calculation to use parseInt() instead of Number(), which would evaluate "" as NaN and let minimumZ be used in such a case.

**Comment by valdrinkoshi** [comment]
@lkovaleva is this still an issue? The PR https://github.com/PolymerElements/iron-overlay-behavior/pull/123 changed it to  `var z1 = Number(overlay.style.zIndex || window.getComputedStyle(overlay).zIndex);`

**Comment by lkovaleva** [comment]
Hi, sorry for the slow response, I will double check this week and follow up, thanks!

**Comment by valdrinkoshi** [comment]
@lkovaleva I'll close this for now, and re-open if the problem persists.

**Comment by lkovaleva** [comment]
Sorry for the delay, I removed our old workaround and verified the issue is fixed, thanks!
