### ISSUE TITLE
Cannot set property offsetWidth of #<HTMLElement> which has only a getter

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/iron-overlay-behavior#135]
I get this error: 
Cannot set property offsetWidth of HTMLElement which has only a getter
In this line 
https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L328

My Chrome version is 49, and here is some info - offsetWidth is read-only property
http://stackoverflow.com/questions/30453078/uncaught-typeerror-cannot-set-property-offsetwidth-of-htmlelement-which-has

One more proof that it's readonly property https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/offsetWidth

**Comment by valdrinkoshi** [comment]
Hi @ellenaua, as written in the comment, this is done because closure compilers would remove that line.
See this example:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520hello(name)%2520%257B%250A%2520%2520var%2520a%2520%253D%2520%257Bok%253A1%257D%253B%250A%2520%2520%252F**%2520%2540suppress%2520%257BsuspiciousCode%257D%2520*%252F%2520a.ok%253B%250A%2520%2520a.ok%2520%253D%2520a.ok%253B%250A%2520%2520alert('Hello%252C%2520'%2520%252B%2520name%2520%252B%2520a)%253B%250A%257D%250Ahello('New%2520user')%253B%250A

Closing this

**Comment by ellenaua** [comment]
I click "compile" and see this var 
a = {ok:1};
a.ok = a.ok;
alert("Hello, New user" + a);
what am I doing wrong?

**Comment by valdrinkoshi** [comment]
Yeah, that's exactly what we want, that line should not be removed. That line is forcing a layout, which is necessary to ensure animations will work properly right after it.

In which browser throws an error?

**Comment by notwaldorf** [comment]
@ellenaua if you only leave the `/** @suppress {suspiciousCode} */ a.ok;` line in, without assigning it to anything, that will be removed by the compiler. See [here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520hello(name)%2520%257B%250A%2520%2520var%2520a%2520%253D%2520%257Bok%253A1%257D%253B%250A%2520%2520%252F**%2520%2540suppress%2520%257BsuspiciousCode%257D%2520*%252F%2520a.ok%253B%250A%2520%2520alert('Hello%252C%2520'%2520%252B%2520name%2520%252B%2520a)%253B%250A%257D%250Ahello('New%2520user')%253B%250A).

**Comment by ellenaua** [comment]
Hi @valdrinkoshi, thanks for help. After some investigation I can explain why that happens for us.

This is jsbin which shows that in **strict** mode code like "div.offsetHeight = div.offsetHeight;" raises an error https://jsbin.com/sazopa/2/edit?html,console,output
In Chrome 49 error is "TypeError: Cannot set property offsetHeight of #<HTMLElement> which has only a getter". In Safari 8 - "TypeError: Attempted to assign to readonly property. (line 4)". I did not check other browsers.

But how does it happen that we have strict mode? This is explanation: we used ES6 in our components. So, as described here - https://www.polymer-project.org/1.0/articles/es6.html - we use "vulcanize", then "crisper" to extract javascript from the generated file, and then "babel" with "es2015" preset to make our components work in all browsers. Babel sets "strict mode" in generated Javascript file. That is why code like "div.offsetHeight = div.offsetHeight;" starts generating an error.

Also, this line https://github.com/PolymerElements/iron-behaviors/blob/master/iron-control-state.html#L90 gives similar error: "checkout.elements.js:171 Uncaught TypeError: Cannot set property focused of #<paper-button> which has only a getter" 

So, these errors appear only if javascript was babelified and strict mode has been set.
I think this info will be useful for other developers, it takes some time to find the reason

**Comment by ellenaua** [comment]
Possible solutions are: 
1) Vulcanize our elements to one file (our.elements.html) and custom elements to another (polymer.elements.html) and apply babelify only to our elements' javascript.
2) Remove 'use strict'; from 1st line of Javascript file generated by babelify
We used solution 2 now.

**Comment by valdrinkoshi** [comment]
Fair point, reopening the issue.
