### ISSUE TITLE
Overlays should not allow scrolling background content (esp in modal mode)

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-overlay-behavior#140]
1. On https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog, resize the window to be very small
2. Notice: the background content is scrollable

Expectation:
The background content (esp with `with-backdrop`) is not scrollable. The paper-dialog should act like a proper modal.

cc @valdrinkoshi @cdata

**Comment by valdrinkoshi** [comment]
WDYT of the following:
- `withBackdrop = false` -> on scroll, close the overlay
- `withBackdrop = true` -> on scroll, block scrolling

In addition we could move `iron-dropdown`'s [`allowOutsideScroll` property](https://elements.polymer-project.org/elements/iron-dropdown#property-allowOutsideScroll) to `iron-overlay-behavior`.

It would be a change in behavior, but not a breaking change.

**Comment by jshcrowthe** [comment]
I 100% agree that when `withBackdrop === true` that scroll should be blocked. 

That said, I don't think that when `withBackdrop === false` that a scroll should **always** close the menu. I can think of use cases where that would be undesirable behavior. The addition of `allowOutsideScroll` effectively solves this as a user would be able to define whether or not the background can scroll based on the use case.

My 2 cents.

**Comment by valdrinkoshi** [comment]
Currently, it is already possible to prevent scrolling by using `Polymer.IronDropdownScrollManager`.
Here an example using `paper-dialog`: http://jsbin.com/purikul/2/edit?html,output

**Comment by ebidel** [comment]
It would be nice if paper-dialog prevented the scrolling for you. `Polymer.IronDropdownScrollManager` isn't documented in our catalog :(

**Comment by kenchris** [comment]
@ebidel I totally agree. And it is not just about scrolling outside the dialog, scrolling pass beginning or endling also scrolls the content.

I find that counter intuitive, you scroll something and then when you reach the end (or beginning), the content behind starts scrolling and most likely the user loses content position and gets confused.

This is not how a modal dialog works on native platforms.

**Comment by kenchris** [comment]
@rbyers commented in the other bug:

This is actually a bit of a whole in the web platform IMHO, see [chromium bug 162179](http://crbug.com/162179). It's not currently possible to prevent scrolls over one element from propagating up to the viewport. People play tricks like consuming wheel events, but that doesn't work for touch. This is much less annoying in browsers that have scroll latching (scroll target never changes within a given gesture) - Safari, Chrome (touch only, soon also wheel), and opt-in in Edge with -ms-scroll-chaining:none. I appreciate any suggestions you have on how the web platform should be extended to fix this (we could just add a CSS property or something).

**Comment by kenchris** [comment]
@ebidel @RByers I think a CSS property would do just fine, but in this case the dialog is modal, so how do you intent a CSS property on that dialog element to prevent events outside?

As I understand you will soon have fixed the worse part, ie any touch/wheel scrolls on the dialog would never move to the parent. So the only part missing is making the dialog modal.

I don't know how the above ```Polymer.IronDropdownScrollManager``` works, but maybe that is the way

**Comment by valdrinkoshi** [comment]
The idea was to basically move `Polymer.IronDropdownScrollManager` into `iron-overlay-behavior` (since `iron-dropdown` implements this behavior).
This manager will listen to a bunch of scroll-causing events like `wheel, mousewheel, touchmove, keydown` and prevent those if needed..also, it sets `overflow: hidden` on `document.body`, causing issues like [this one](https://github.com/PolymerElements/iron-dropdown/issues/54). Consider that listening to these events might have perf consequences on scrolling smoothness (especially on mobile). 
I'm a bit afraid to introduce this to all overlays, at least until these issues are solved in `Polymer.IronDropdownScrollManager`

**Comment by kenchris** [comment]
@RByers can you look at the above, now you are our scrolling event expert? :-) Maybe look at how IronDropdownScrollManager is implemented

**Comment by markovuksanovic** [comment]
+1

**Comment by SPAHI4** [comment]
+1

**Comment by vinerz** [comment]
+1, just had a dialog dancing on iOS while scrolling the document with the dialog open.. 😢
