### ISSUE TITLE
The on-screen keyboard incorrectly sizes iron-overlay-backdrop

### ISSUE THREAD

**Issue by jdbence** [PolymerElements/iron-overlay-behavior#149]
### Description
The `iron-overlay-backdrop` is incorrectly sized when the on-screen keyboard is shown. It is the size of the viewport but it should be the size of the page.
```js
// what I'm doing now to resolve the issue
iron-overlay-backdrop {
 /*width: 100vw;*/
 /*height: 100vh;*/
 width: 100%;
 height: 100%;
}
```
### Expected outcome
The `iron-overlay-backdrop` should cover the entire page

### Actual outcome
The `iron-overlay-backdrop` is only the size of the viewport

### Steps to reproduce
1. Create a `paper-dialog` with an `input` element
2. Open the page on a iPad browser
3. Tap the input element

### Browsers Affected

- [x] Chrome (iPad)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Hi @jdbence, I tested this http://jsbin.com/vukusa/2/edit?html,output on Chrome 46 and Chrome 49 for iPad and could not reproduce the issue.
Can you provide a jsbin to show the bug?

**Comment by jdbence** [comment]
Sure, I modified your example by adding a class to the body.
[http://jsbin.com/votavi](http://jsbin.com/votavi)

**Comment by valdrinkoshi** [comment]
Thanks!
