### ISSUE TITLE
iron-overlay-manager clicking outside paper-dialog dont close it

### ISSUE THREAD

**Issue by TomaszPasternak** [PolymerElements/iron-overlay-behavior#153]
### Description
After clicking ouside of not modal paper-dialog nothing happen.

### Expected outcome
Dialog should close.

### Actual outcome
Dialog is visible.

### Steps to reproduce

1. Put a `paper-dialog` element in the page.
2. Open the page in a web browser.
3. Click outside of the `paper-dialog` element.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11

Others not tested.

### Additional information

This is propably caused by changes in commit [https://github.com/PolymerElements/iron-overlay-behavior/commit/a06a02930590237020581a3acfd9b935aa9b5bbf](https://github.com/PolymerElements/iron-overlay-behavior/commit/a06a02930590237020581a3acfd9b935aa9b5bbf)

**Comment by valdrinkoshi** [comment]
Hi @TomaszPasternak, I don't see the issue you describe http://jsbin.com/ripahu/1/edit?html,output
Closing this for now, please provide a snippet showing the bug & I'll reopen this ;)

**Comment by TomaszPasternak** [comment]
Hi @valdrinkoshi, This issue take place only in newest version of Chrome. The example you provide dont work in Chrome for me.

Did you check this in Chrome?

**Comment by valdrinkoshi** [comment]
Yes, latest Chrome on mac
![all-good](https://cloud.githubusercontent.com/assets/6173664/14437661/2275e00a-ffd7-11e5-82d3-bd34b7ff2705.gif)
