### ISSUE TITLE
An anchor link behind a backdrop reacts with tap on closing the backdrop

### ISSUE THREAD

**Issue by naoak** [PolymerElements/iron-overlay-behavior#160]
### Description
An anchor link behind a backdrop unintentionally reacts with a tap action as soon as the backdrop has closed.

I guess this is a regression related to #148.

### Expected outcome
The anchor does not react with the tap while the backdrop is closing.

### Actual outcome
The anchor reacts with the tap, and jumps to the link.

### Live Demo
http://jsbin.com/hebacicize/edit?html,console,output

### Steps to reproduce

1. Tap a `paper-button` in the page. (will open a backdrop)
2. Tap the backdrop just around on a link.

### Browsers Affected
- [x] Moboile Chrome
- [x] Moboile Safari

**Comment by valdrinkoshi** [comment]
Hi @naoak, thanks for reporting this! yeah, the `iron-overlay-manager` should be listening for `tap` instead of `touchstart`.
