### ISSUE TITLE
`iron-overlay` is not closed on outside click when device supports touch + mouse. e.g. Windows 10 laptop with touch support.

### ISSUE THREAD

**Issue by ChiragMoradiya** [PolymerElements/iron-overlay-behavior#174]
### Description
`iron-overlay` is not closed on outside click when device supports touch + mouse. e.g. Windows 10 laptop with touch support.

### Expected outcome
`iron-overlay` should be closed on outside click when device supports touch + mouse. For outside touch it's working.

### Actual outcome
`iron-overlay` is not closed on outside click when device supports touch + mouse. For outside touch it's working.

### Steps to reproduce
Sorry, I am skipping this as I guess, title it self is enough explaining issue. 

### Browsers Affected
All

**Comment by AndreasGalster** [comment]
Thanks for figuring out the reason! I thought I would go crazy when trying to find the root cause of this bug!

**Comment by ChiragMoradiya** [comment]
I have fixed this in my forked branch. I will submit merge request in a day or two.

**Comment by valdrinkoshi** [comment]
It is fixed in this PR https://github.com/PolymerElements/iron-overlay-behavior/pull/181 and it will be merged & released in the following days :+1:
