### ISSUE TITLE
Loop in iron-overlay-manager

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-overlay-behavior#18]
_From @dsportes on June 14, 2015 12:15_

I have a modal paper dialog opening a second modal paper-dialog.
This causes a loop (Maximum call stack exceed) in two different locations :
iron-overlay-manager.html line 63
paper-dialog-manager.htm line 210
I didn't find any workaround.
Regards

_Copied from original issue: Polymer/polymer#1864_

**Comment by tjsavage** [comment]
_From @dsportes on June 14, 2015 15:1_

I patched iron-overlay-manager.html at line 74 with: 
        setTimeout(function() {current._applyFocus();}, 100);
and paper-dialog-behavior.html at line 210 with:
        	  if (!document.hasFocus()) {
		            if (this._lastFocusedElement) {
		              this._lastFocusedElement.focus();
		            } else {
		              this._focusNode.focus();
		            }
        	  }
Issues "seem" to be solved but I'm not really confident why :-)
Regards

**Comment by tjsavage** [comment]
_From @sorvell on June 15, 2015 23:21_

This issue tracker is for the Polymer core library. We'll make sure this is moved to an appropriate location.

**Comment by ronnyroeller** [comment]
+1

**Comment by cdata** [comment]
Closing this, as I believe the bug is fixed. Please re-open if it is still a problem!
