### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by alvarouribe** [PolymerElements/iron-overlay-behavior#185]
### Description
The `README.md` page could be better explaining how to utilise this element

### Expected outcome

Add a quick example or add a reference to the demo page to see an easy example.
I wish that all elements would have the same easy way to explain how to implement/use it
Maybe a small 4 step tutorial to use it

### Actual outcome

explains the behaviour of the element without explain how to implement it

### Documentation Affected
All

**Comment by valdrinkoshi** [comment]
@arthurevans FYI

**Comment by valdrinkoshi** [comment]
In general, behaviors should be used/implemented as [explained here](https://www.polymer-project.org/1.0/docs/devguide/behaviors). In the catalog, it would be helpful to have this link available when the user is on a behavior.
In the catalog demo pages, it is currently not possible to "easily" access to the implementation of test elements (e.g. `simple-overlay`):
<img width="450" alt="screen shot 2016-05-20 at 10 29 16 am" src="https://cloud.githubusercontent.com/assets/6173664/15436262/d2f9e37e-1e75-11e6-852c-370cc1296370.png">
The only way to do that is to either open the dev-tools, or to click on `source` on the left drawer-panel of the catalog, and navigate to `demo/simple-overlay.html`.

**Comment by wyattallen** [comment]
The documentation should describe the focus-wrapping feature. Focus wrapping can cause issues such as #184 and #188 and are likely not an expected feature of an overlay. For my part, I had to dig into the source-code to discover the feature and diagnose my issue with it.
