### ISSUE TITLE
/deep/ combinator is deprecated.

### ISSUE THREAD

**Issue by jay8t6** [PolymerElements/iron-overlay-behavior#189]
Import to iron-fit-behavior.html is causing the following warning in console.
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details. 

I am not sure if this should be filed under iron-fit-behavior repo or this repo needs the latest version of iron-fit-behavior (I see that you are using 1.0.0, but the latest version of iron-fit-behavior is 1.2.2)

**Comment by valdrinkoshi** [comment]
All the imports done in `iron-overlay-behavior` are either other behaviors (which don't have any style).
The only one with styles defined is `iron-overlay-backdrop`, which doesn't have any /deep/ selector.

`iron-fit-behavior` as well doesn't define any style, it's only importing `polymer/polymer.html`.
It doesn't seem related to `iron-fit-behavior` or `iron-overlay-behavior`: could you provide more details?

**Comment by valdrinkoshi** [comment]
Closing this for now (21 days without a response)
