### ISSUE TITLE
iron-overlay-{opened,closed} events called before overlay is opened/closed

### ISSUE THREAD

**Issue by wyattallen** [PolymerElements/iron-overlay-behavior#191]
### Description
The `iron-overlay-opened` is emitted **before** the overlay is opened. Additionally, the `iron-overlay-closed` event is emitted **before** the overlay is closed.

The iron-overlay-behavior documentation specifically say the following. (Emphasis mine.)
* `iron-overlay-closed` Fired **after** the overlay closes.
* `iron-overlay-opened` Fired **after** the overlay opens.

### Expected outcome
Expect that the opened and closed events are not emitted until the overlay is opened or closed respectively.

### Actual outcome
The events are emitted before their corresponding UI change.

### Live Demo
[Live Demo](http://jsbin.com/guneha/edit?html,output)

### Steps to reproduce
1. Attach listeners to the `iron-overlay-opened` and `iron-overlay-closed` events.
2. Open the overlay.
3. The opened event is emitted before the overlay appears.
4. Close or cancel the overlay.
5. The closed event is emitted before the overlay has disappeared.

### Browsers Affected

- [x] Chrome

**Comment by valdrinkoshi** [comment]
Hi @wyattallen, I think this is related to the fact that you're using `alert` which seems to take precedence to the finishing of the animation (seems like it interrupts it until you dismiss the alert).
In any case, if you use `document.elementFromPoint` to see what's the element in the center of the screen, you'll see that it will return elements in the `x-overlay` when it is opened.
http://jsbin.com/kebasaj/1/edit?html,output

**Comment by wyattallen** [comment]
@valdrinkoshi Thanks. I see what you mean. Although it does seem a little nonintuitive for the event to fire before the animation is complete. Closing.

**Comment by valdrinkoshi** [comment]
@wyattallen the event is fired after the animation is complete.
`iron-overlay-behavior` by default doesn't have any animation, while the `iron-overlay-backdrop` does. 

If you animate the overlay, you'll see it rendered when the alert is fired http://jsbin.com/kebasaj/3/edit?html,output
