### ISSUE TITLE
focus issue specific to the versions used

### ISSUE THREAD

**Issue by vehsakul** [PolymerElements/iron-overlay-behavior#204]
### Description
wrong input traversal order when pressing TAB,

iron-overlay-behavior doesn't consider inputs as focusables (put a breakpoint [here](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L222))

### Expected outcome

when pressing TAB and the focus is on the first input, the following input gets focused

### Actual outcome

the button gets the focus (the following input elements are ignored)

### Live Demo
https://plnkr.co/edit/oMjA8r

**Comment by valdrinkoshi** [comment]
This is similar to the issue reported here https://github.com/PolymerElements/iron-overlay-behavior/issues/192, and is being solved in PR #200. Will close this as it's a duplicate.
