### ISSUE TITLE
Order of focusable elements gets messed up by tabIndex sorting

### ISSUE THREAD

**Issue by andreasanheuser** [PolymerElements/iron-overlay-behavior#209]
### Description
`get _focusableNodes()` uses `Array.sort` to sort focusable elements by `tabIndex` ([see here](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L228)). However, `Array.sort` is not guaranteed to be stable ([see documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)). This leads to the order of focusable elements getting messed up and makes `__first/__lastFocusableNodes` point to incorrect nodes which results in unexpected behavior when using the tab key to sequentially walk through focusable nodes.

E.g. in Chrome it can be reproduced once the array has more than 10 elements: https://jsbin.com/rurowalosa/edit?js,console

**Comment by valdrinkoshi** [comment]
Thanks for reporting, @andreasanheuser! Sorting by tabindex shouldn't be necessary, as using tabindex > 0 is considered an anti-pattern. [In this PR](https://github.com/PolymerElements/iron-overlay-behavior/pull/200/files#diff-85329e739caff16e918d7795425ad390R26) (still under review) we avoid sorting if not necessary. I'll look into solving the issue there
