### ISSUE TITLE
 restoreFocusOnClose should only show visible focus when restoring with keyboard

### ISSUE THREAD

**Issue by helenxywu** [PolymerElements/iron-overlay-behavior#210]
### Description
When restoreFocusOnClose is on, when user exits out of iron overlay, the focus is visible on the item the focus was restored to. This is the correct behavior for keyboard navigation, but not mouse navigation. This causes an awkward focus ring after the user exits using mouse.

### Expected outcome

The focus should show if restored focus using keyboard, but focus ring should not show when restored focus using mouse.

### Actual outcome

The focus ring shows if restored focus using mouse and doesn't disappear until another mouse click.

**Comment by valdrinkoshi** [comment]
Hi @helenxywu, the element receiving the focus is responsible of showing or not the focus ring. 

`iron-overlay-behavior` will move the focus to that element on close if `restoreFocusOnClose = true`. It will handle the "when", and delegate the "how" to the elements implementing this behavior, which can do that by:
- setting `restoreFocusOnClose` according to the closing reason (e.g. if overlay is canceled via `esc` restore, else don't)
- exposing this property to the end user if needed, to provide even more customization

Some examples: `iron-dropdown` should set `restoreFocusOnClose = true` only if canceled via esc key, while `paper-dialog-behavior` should set it to true also if the user tapped on `dialog-dismiss` or `dialog-confirm`

**Comment by helenxywu** [comment]
The examples are not setting restoreFocusOnClose; also we wouldn't want the focus to restore if the event was on a tap, only if it was a keyboard event.
