### ISSUE TITLE
iron-overlay-behavior throws an error 'Uncaught SyntaxError: Invalid or unexpected token'

### ISSUE THREAD

**Issue by mshahidkhan** [PolymerElements/iron-overlay-behavior#216]
### Description

iron-overlay-behavior throws an error 'Uncaught SyntaxError: Invalid or unexpected token'.

It looks like browser is interpreting Commented header section of iron-overlay-behavior.html differently.
I see a script inserted in the commented section. Please refer attached screenshot.

**I didn't see the issue in localhost but when I access my QA/Dev server, I see the issue.**
Verified that there is nothing wrong in the iron-overlay-behavior.html

> Solution - Remove the commented section, issue fixed! 

Did anybody faced any such thing before ?
I expect that if I minify my code, it should solve the issue. But I would like to know the reason behind this behavior.
### Expected outcome

Any component that uses overlay behavior should work properly.

### Actual outcome

It's breaking any page that is using overlay behavior. Overlay appears on the page as black colored boxes.
### Steps to reproduce

Sorry, Do not have the steps to reproduce. 
Please refer the attached screenshots.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
  ![image](https://cloud.githubusercontent.com/assets/8899379/18554310/767dc1ea-7b29-11e6-8141-05b9293d644a.png)
  ![image](https://cloud.githubusercontent.com/assets/8899379/18554324/811ee494-7b29-11e6-8695-456cd1a012cc.png)

**Comment by valdrinkoshi** [comment]
Seems like the QA/Dev server sees `<body>` in [line 46](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L46) but doesn't realize it is in comment block. Could you check/share how are you deploying?

**Comment by ardean** [comment]
@valdrinkoshi thank you for your quick response, removing <body> works for me!
This problem occurs only in Firefox. Chrome, Safari and Internet Explorer are not affected by this.
Everything is served by browser sync.

**Comment by valdrinkoshi** [comment]
Looks a problem in your tooling, some of it has a bad html parser that doesn't recognize it is in a comment section. It looks like it inserts beacon scripts in any html found on its way.
Are you using any polymer-issued tooling?

**Comment by mshahidkhan** [comment]
It works if vulcanize or minification is done OR manually removing the comment.
We use IIS server and no minification for local environments.

The open questions are -
1. Why is it happening ? Why only with iron-overlay-behavior ?
2. What can be done (other than removing comments via vulcanize/task runner).
3. What change brought this issue? (it was not there before and I have not updated my iron-overlay-layout for last 4 months)

Don't agree with -> "Use Polymer-issued tooling and fix it " without knowing the actual reason.

**Comment by valdrinkoshi** [comment]
I don't know why this is happening, I just see that your server changes this
```
### Backdrop
Set the `with-backdrop` attribute to display a backdrop behind the overlay. The backdrop is
appended to `<body>`
```
to this
```
### Backdrop
Set the `with-backdrop` attribute to display a backdrop behind the overlay. The backdrop is
appended to `<script type="text/javascript">window.NREUM|| ....
```
I assume that deep down that script there is a comment as well and it ends with */ which closes the comment block and creates the issue.

So I suggest you find who is replacing `<body>` to `<script type="text/javascript">window.NREUM||`.
Possible solutions:
- Make that tool skip the polymer elements folder
- Remove comments from that beacon script 
- Vulcanize polymer elements

cc/ @justinfagnani who might further help on this

**Comment by ardean** [comment]
@valdrinkoshi you're right! browsersync causes this issue in my case.
Thank you for your support.

![photo](https://cloud.githubusercontent.com/assets/17138728/18764121/685ac788-8110-11e6-8613-df242e7c0ccb.png)

**Comment by valdrinkoshi** [comment]
@mshahidkhan can I close this issue or the problem still persists for you?

**Comment by mshahidkhan** [comment]
@valdrinkoshi yes, you may close it. 
Thanks.
