### ISSUE TITLE
get deepActiveElement needs to check if it's a svg

### ISSUE THREAD

**Issue by flyingfish2016** [PolymerElements/iron-overlay-behavior#217]
When the activeElement is a svg, it couldn't be focus via "focus" method.

  _prepareRenderOpened: function() {
      // Store focused node.
      this.__restoreFocusNode = this._manager.deepActiveElement;

      // Needed to calculate the size of the overlay so that transitions on its size
      // will have the correct starting points.
      this._preparePositioning();
      this.refit();
      this._finishPositioning();

      // Safari will apply the focus to the autofocus element when displayed
      // for the first time, so we make sure to return the focus where it was.
      if (this.noAutoFocus && document.activeElement === this._focusNode) {
        this._focusNode.blur();
        this.__restoreFocusNode.focus();
      }
    },

Added the below code in my project to fix this issue temporarily when it's a svg:
   `(Polymer as any).IronOverlayManagerClass.prototype.__defineGetter__("deepActiveElement", function ()
{
    // document.activeElement can be null
    // https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
    // In case of null, default it to document.body.
    var active: any = document.activeElement || document.body;
    while (active.root && (<any>Polymer.dom(active.root)).activeElement)
    {
        active = (<any>Polymer.dom(active.root)).activeElement;
    }

    if (active.tagName == "svg")
    {
        active = active.parentElement || document.body;
    }
    return active;
});`

**Comment by valdrinkoshi** [comment]
Hi @flyingfish2016, in which browser do you see this issue? If that happens in IE/Edge, PTAL at this PR https://github.com/PolymerElements/iron-overlay-behavior/pull/211, you might want to try the suggested workaround https://github.com/PolymerElements/iron-overlay-behavior/pull/211#issuecomment-239552801

**Comment by flyingfish2016** [comment]
Hello valdrinkoshi, it happens in IE/Edge. 

The exception throws at this line: this.__restoreFocusNode.focus();
Object doesn't support property or method 'focus'

**Comment by valdrinkoshi** [comment]
This is an issue on IE/Edge https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8479637/
Please see the provided solution there or in this thread https://github.com/PolymerElements/iron-overlay-behavior/pull/211#issuecomment-248703508

Closing this
