### ISSUE TITLE
[Firefox] SyntaxError: unterminated comment

### ISSUE THREAD

**Issue by birkir** [PolymerElements/iron-overlay-behavior#22]
On line 41 in iron-overlay-behavior.html is a &lt;body&gt; tag that failes in Firefox.

Console log reports
```
SyntaxError: unterminated comment
```

The output of that file is
```
### Backdrop

Set the `with-backdrop` attribute to display a backdrop behind the overlay. The backdrop is
appended to `<body><script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.7.7.js'><\/script>".replace("HOST", location.hostname));
//]]>
//# sourceURL=http://localhost:3000/bower_components/iron-overlay-behavior/iron-overlay-behavior.html.js
```

**Comment by cladera** [comment]
The same here.

Tested with Firefox v38.0 & v39.0 OS X Yosemite, 10.10.4 and Firefox v38.0 x-Ubuntu 14.04

It seems Firefox interprets tags within comments. I removed '<' and '>'  characters from comments and it worked.

**Comment by vhdirk** [comment]
The real issue here lies with browserSync.
browserSync searches for the ```<body>``` tag and injects its scripts right after it.

This report shows a few options to solve it: https://github.com/PolymerElements/polymer-starter-kit/issues/126

**Comment by cdata** [comment]
Closing this, as it does not seem to be an `IronOverlayBehavior` issue.
