### ISSUE TITLE
Can't dismiss overlay by clicking inside an iframe in the same document.

### ISSUE THREAD

**Issue by eliseosoto** [PolymerElements/iron-overlay-behavior#220]
### Description
The overlay can't be dismissed by clicking outside it if the click is on an iframe embedded in the parent document.

### Expected outcome
The overlay should be dismissed because the user clicked outside it within the same document.

### Live Demo
Example: https://plnkr.co/edit/ibiIKMM4Ez5pkdvXsOAY

### Steps to reproduce

1. Open the live demo.
2. Click on the "Plain overlay" button to open the overlay.
3. Try to dismiss the overlay by clicking anywhere in the iframe.
4. Click anywhere else in the document and the overlay is dismissed correctly.

### Browsers Affected

- [x] Chrome (only tested in Chrome).

**Comment by valdrinkoshi** [comment]
`click` event cannot be captured when it happens in an iframe even if we use `useCapture = true` http://jsbin.com/qorino/1/edit?html,output
The only way to work around this is disable the iframe interactions when the overlay is opened by setting `pointer-events: none`
