### ISSUE TITLE
backdrop is not defined

### ISSUE THREAD

**Issue by hinderer-matthieu** [PolymerElements/iron-overlay-behavior#222]
### Description
Hello,
When I use this sample code from this [page](https://beta.webcomponents.org/element/PolymerElements/iron-overlay-behavior/demo/demo/index.html) on chrome:

```
<button onclick="backdrop.open()">Overlay with backdrop</button>
<simple-overlay id="backdrop" with-backdrop>
  <p>Hello world!</p>
  <button>Button</button>
  <button onclick="backdrop.close()">Close</button>
</simple-overlay>
```

It works on polymer's website but in my case I get this error:
_index.html:1 Uncaught ReferenceError: backdrop is not defined
    at HTMLButtonElement.onclick (index.html:1)_

### Browsers Affected
Chrome

### Browsers OK
Firefox

**Comment by ampersand8** [comment]
I'm having the exact same issue with the plain example. Works fine in Firefox but not Chrome.

_list-projects:1 Uncaught ReferenceError: plain is not defined
    at HTMLElement.onclick (list-projects:1)_

**Comment by valdrinkoshi** [comment]
Yes, please see this discussion for further info https://github.com/PolymerElements/paper-dialog/issues/128#issuecomment-248773545
