### ISSUE TITLE
After reattaching, opened state is set to false but element remains visible

### ISSUE THREAD

**Issue by ocarvajal** [PolymerElements/iron-overlay-behavior#223]
### Description
I'm using a paper-menu-button with closeOnActivate on. One of the options of the menu makes the container element to be removed from the DOM and replaced with a second element. Yet, from the second element I can choose to switch back to my first element withe menu. This brings the dropdown element into an inconsistent state where opened is false, but the element is visible.

### Expected outcome
When I reattach my first element back into the DOM, the menu should not be expanded.

### Actual outcome
When I come back to the first element, the menu is always already opened. After some deep investigation I found that the drop-down(iron-overlay) is closed (opened=false), but the style.hidden is set to '' (visible).
Clicking outside of the menu or selecting any menu option don't close the menu anymore because the dropdown state is already closed and the event doesn't propagate all the way to the end.
I realized that in the detached function, the call that was meant to happen via requestAnimationFrame() is cancelled.

FYI, for the moment I'm forcing a call to __openedChanged() when I detect this inconsistent state in the dropdown.

**Comment by valdrinkoshi** [comment]
Basically the overlay gets detached while animating...nice one, thanks for reporting @ocarvajal!
