### ISSUE TITLE
Polymer 2.0 - Polymer.Gestures.add has been privatized

### ISSUE THREAD

**Issue by TomK** [PolymerElements/iron-overlay-behavior#232]
This [Polymer 2.0 PR](https://github.com/Polymer/polymer/pull/4312) appears to have refactored the `Polymer.Gestures.add` method to `Polymer.Gestures._add` [here](https://github.com/Polymer/polymer/pull/4312/files#diff-20794b26841d6321df19e97b3f198111L342)

This affects [iron-overlay-manager#L43](https://github.com/PolymerElements/iron-overlay-behavior/blob/2.0-preview/iron-overlay-manager.html#L43) which now throws the following error:
![image](https://cloud.githubusercontent.com/assets/299656/23168253/7859884e-f83f-11e6-8dcb-b66ec107285a.png)

**Comment by valdrinkoshi** [comment]
This should be reverted in polymer#2.0-preview to avoid breaking changes, please follow here https://github.com/Polymer/polymer/issues/3936
Closing this
