### ISSUE TITLE
TypeError: t.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by camargo** [PolymerElements/iron-overlay-behavior#235]
### Description
This is the same issue as #44.

### Expected outcome

No error should be thrown.

### Actual outcome

Getting the error in the console:

`TypeError: t.getBoundingClientRect is not a function`

This is being triggered by https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L46

![capture](https://cloud.githubusercontent.com/assets/683355/24310335/bdb98906-108c-11e7-8e9b-ed19ece13b6a.PNG)

### Steps to reproduce

1. Open Firefox
2. Go to https://www.webcomponents.org/element/PolymerElements/iron-overlay-behavior/demo/demo/index.html
3. Make your window smaller than your screen
4. Click down on the `Plain overlay` button
5. Drag your cursor **while still clicked down** outside of the browser window
6. Release click outside the browser window
7. The error will be in the console

### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
In Firefox apparently the `event.target` is `document`, while in the other browsers is `document.documentElement` (aka `<html>`), see a simpler repro http://jsbin.com/mabisob/2/edit?html,console,output
This issue should be resolved in `Polymer.Gestures`, will move the issue there.

**Comment by valdrinkoshi** [comment]
This issue was moved to Polymer/polymer#4459

**Comment by camargo** [comment]
@valdrinkoshi Right now the gesture is being added to `document` (https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L46). Could we add it to `body` or `html`. That could fix the issue.

**Comment by valdrinkoshi** [comment]
I'd do `document.documentElement` for all of these https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L46-L49 👌
PRs welcome 😃

**Comment by camargo** [comment]
@valdrinkoshi Alright that should do it, please ignore the first one
