### ISSUE TITLE
polymer-cli build

### ISSUE THREAD

**Issue by lequem** [PolymerElements/iron-overlay-behavior#244]
When building the polymer application with polymer-cli version 0.18.1, the following error occurs: "Unable to resolve behavior `Polymer.IronOverlayBehaviorImpl"  . Did you import it? Is it annotated with @polymerBehavior?

**Comment by valdrinkoshi** [comment]
@lequem is this still happening with polymer-cli 1.5.x?

**Comment by lequem** [comment]
No, it's ok. You can close the ticket, thank you

**Comment by lequem** [comment]
No, it's ok. You can close the ticket, thank you
