### ISSUE TITLE
Restore focus not working as expected

### ISSUE THREAD

**Issue by ruud** [PolymerElements/iron-overlay-behavior#247]
### Description
When restore-focus-on-close is set on a paper-dialog (which implements this behavior), the restoreFocusNode does not get its focus back, when the dialog is canceled and/or closed. The isAttached check added prevents the right part being called.

### Expected outcome
The focus is restored on the restoreFocusNode

### Actual outcome
The focus is lost and falls back to the first focusable item on the page.

### Steps to reproduce

1. Put a `paper-dialog` element with `restore-focus-on-close` attribute in the page.
2. Open the page in a web browser.
3. Click the `open-dialog` button.
4. Close the dialog.
5. The restore focus is not set on the button.

### Browsers Affected

- [x] Chrome

**Comment by valdrinkoshi** [comment]
Cannot repro - see https://www.webcomponents.org/element/PolymerElements/iron-overlay-behavior/demo/demo/index.html
![restore-focus](https://cloud.githubusercontent.com/assets/6173664/26602534/a7ecfcda-4538-11e7-813c-2edc73a3756d.gif)

Same with paper-dialog, see http://jsbin.com/hezuliwepi/1/edit?html,output

**Comment by ruud** [comment]
@valdrinkoshi , this remains an issue when the dialog is detached from the DOM before the animation cycle is complete. Thats why I added the pull-request https://github.com/PolymerElements/iron-overlay-behavior/pull/246

**Comment by valdrinkoshi** [comment]
@ruud oh I see, that wasn't clear on the description.
I don't think it should restore the focus if it's already detached, e.g.
```js
dialog.parentNode.removeChild(dialog);
dialog.opened = false; // <-- should not restore focus
```
If you close it and then detach it, the focus should be restored in the next animation frame after it gets closed, e.g.
```js
dialog.opened = false; // <-- should restore focus
dialog.parentNode.removeChild(dialog);
```
I can handle this in this PR, as it's related to detaching an animating overlay https://github.com/PolymerElements/iron-overlay-behavior/pull/230
