### ISSUE TITLE
Overlay causing an exception when used in Polymer Shop app on Edge 15

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/iron-overlay-behavior#249]
It looks like [this issue](https://github.com/Polymer/polymer/issues/4620) is being caused by passing a `null` handler [here](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L47). 

This occurs when using Polymer 1.9.1 and Edge 15 only.

**Comment by valdrinkoshi** [comment]
Having a hard time installing the VMs to verify if this works fine with Polymer 1.7 or earlier.
If the native `document.documentElement.addEventListener('tap', null)` works, then isn't it a regression introduced in Polymer?

**Comment by michabaur** [comment]
I get this error, too. Seems the Edge doesn't like 'null' event listeners. In my tests, each of the following lines throws this error (in a plain html file): 
```javascript
  document.documentElement.addEventListener("tap", null);
  document.documentElement.removeEventListener("tap", null);
  document.documentElement.addEventListener("click", null);
  document.documentElement.removeEventListener("click", null);
```

**Comment by valdrinkoshi** [comment]
Tested on MSEdge 15 and can't reproduce the issue
<img width="1026" alt="screen shot 2017-07-19 at 12 25 55 pm" src="https://user-images.githubusercontent.com/6173664/28385578-7d997d52-6c7d-11e7-8de2-3bf8b2b03f65.png">

**Comment by michabaur** [comment]
I can reproduce it in actual scripts in the document but indeed not in the console. Also, I get the error only if the dev tools are open. I don't know whether that means that the error is only triggered by the dev tools or that edge doesn't show errors that happened before opening dev tools.

![edge-repro](https://user-images.githubusercontent.com/13118223/28514908-05274f2e-705c-11e7-88d2-a3b39f6c6393.PNG)

**Comment by valdrinkoshi** [comment]
Filed an issue here https://github.com/Microsoft/ChakraCore/issues/3863
