### ISSUE TITLE
Opened property is changed twice on click of cancel or open methods

### ISSUE THREAD

**Issue by mohan-subbu** [PolymerElements/iron-overlay-behavior#256]
changing of value for "opened" property is happening twice when we click(i.e. bubbling) ,using the methods cancel() and open() of this behavior.

So, even if we execute close() or cancel() method still it returns the value of 'opened' as **true**

**Comment by valdrinkoshi** [comment]
Could you provide steps to reproduce? From this example it seems to work as expected http://jsbin.com/rotoqoy/1/edit?html,output
