### ISSUE TITLE
Implement `always-on-top`

### ISSUE THREAD

**Issue by morethanreal** [PolymerElements/iron-overlay-behavior#3]
aka `layered`

**Comment by wuxiaoying** [comment]
+1

**Comment by kbwatts** [comment]
+1

**Comment by jasonku09** [comment]
+1

**Comment by ronnyroeller** [comment]
+1

**Comment by valdrinkoshi** [comment]
Let's add more details for how this should work:
- the overlay with `always-on-top` should match the `Polymer.IronOverlayManager.currentOverlay()` even if other overlays are opened after it
- if there is more than one overlay with `always-on-top`, the last one to be opened wins (is on top)
- `with-backdrop` doesn't affect `always-on-top`

This should be handled in the manager's `addOverlay` method (take care of updating `z-indexes` too!)
