### ISSUE TITLE
Overlay closes itself on adding click event on any element inside overlay and doing event.stopPropagation inside the handler

### ISSUE THREAD

**Issue by krunal1988** [PolymerElements/iron-overlay-behavior#30]
Scenario:
I have used iron overlay behavior and made overlay component. I have DOM element which i show inside the overlay as content and which has a click handler. Inside click handler i have done e.stopPropagation and when i click that element overlay closes it self.

I remove  the stopPropagation the overlay remains open even after clicking the element.

**Comment by dChin84** [comment]
The overlay seems to capture clicks I presume to close if you click outside. You can force it from closing by setting noCancelOnOutsideClick.

**Comment by bicknellr** [comment]
@krunal1988 I can't repro this issue, here's a demo to try out: http://jsbin.com/loxuhayare/edit?html,output. It has an overlay containing a couple buttons with different types of click event listeners which call `stopPropagation`, but the overlay doesn't close when clicking the buttons. Does this problem still occur in your context?

**Comment by valdrinkoshi** [comment]
Closing this, will re-open if needed.
