### ISSUE TITLE
Error after component update.

### ISSUE THREAD

**Issue by albertolobrano** [PolymerElements/iron-overlay-behavior#39]
I recently updated all my modules and this error is coming up.  Not sure if it is a bug or something i am doing wrong. 

Uncaught TypeError: Cannot read property 'toString' of nullobj.addEventListener @ polydev/vendor/zone-microtask.js:973Gestures.add @ polymer.html:673Polymer.IronOverlayBehaviorImpl._toggleListener @ iron-overlay-behavior.html:262(anonymous function) @ iron-overlay-behavior.html:280fnNames.map.forEach.global.zone.(anonymous function).arguments.(anonymous function) @ polydev/vendor/zone-microtask.js:406(anonymous function) @ polydev/vendor/zone-microtask.js:98run @ polydev/vendor/zone-microtask.js:118zoneBoundFn @ polydev/vendor/zone-microtask.js:91

**Comment by albertolobrano** [comment]
This issue was caused by polydev extention tool in chrome.

**Comment by samccone** [comment]
@albertolobrano do you happen to have a small test case that will make polydev fail¿

**Comment by albertolobrano** [comment]
No i do not have any test that i can send you .  This is what i did 
1) polydev installed in chrome
2) application based on polymer starting kit 
3) created a  modal like this      
  <paper-dialog modal="true" opened="{{!session}}" modal class="app fit" noCancelOnEscKey noCancelOnOutsideClick>

it fails with the stack trace i posted. 

I hope this can help you. If you need any more information let me know.
