### ISSUE TITLE
Iron overlays within iron overlays have multiple issues

### ISSUE THREAD

**Issue by NickBlow** [PolymerElements/iron-overlay-behavior#43]
Opening an iron overlay within another iron overlay has a few issues.

Firstly : When adding a backdrop, if you open a second overlay, the second backdrop has the wrong z-index, and when you close the second overlay, the background does not go away.

Opening the first overlay  - note the backdrop z-index of 11.

![overlay 1](https://cloud.githubusercontent.com/assets/6502020/10278462/6de2e2c0-6b55-11e5-82f2-35263e3ac9b6.jpg)
 
Opening the second overlay. The backdrop does not have the right z-index (it's 9, when it should be higher than 11). Additionally, it does not have the 'opened' attribute.
![overlay 2](https://cloud.githubusercontent.com/assets/6502020/10278473/82c4eb66-6b55-11e5-82b2-f393c6f44380.jpg)

On closing the second overlay backdrop 2 stays, and when then closing the first overlay, backdrop 1 disappears, but backdrop 2 stays on top of the page. Note how backdrop 1 (with z-index 11) has disappeared, but backdrop 2 with z-index 9 is still there.

![overlay 3](https://cloud.githubusercontent.com/assets/6502020/10278521/da97d7f4-6b55-11e5-93ab-a09ab14ccac4.jpg)

Additionally, pressing escape with both overlays open closes both of them, when you would expect it to only close the one on top.

For our use case having overlays within a full page overlay makes sense, but it may be that they weren't designed to be layered in the first place?

**Comment by valdrinkoshi** [comment]
@NickBlow all the reported issues have been fixed:
- there is only 1 backdrop element that is shared across overlays
- `z-index` is correctly updated for overlays and backdrop
- only top overlay gets closed on ESC (fixed in https://github.com/PolymerElements/iron-overlay-behavior/pull/82)
