### ISSUE TITLE
Tap causes type error to occur in firefox and safari 

### ISSUE THREAD

**Issue by dChin84** [PolymerElements/iron-overlay-behavior#44]
In firefox or safari using iron-overlay-behavior 1.0.7+ tapping outside the element causes a type error to occur in the handleNative fn. After some investigation it seems like ev.currentTarget is not the document node with __polymerGestures attached too which should of been assigned from a call to Polymer.Gestures.add within _toggleListeners when opened. Could this possibly be something todo with event forwarding? the correct node is wrapped up in __imp** not currentTarget.

**Comment by cdata** [comment]
Hi, I'm unable to reproduce this on the `IronOverlayBehavior` demo. Could you provide a test case and re-open? Thanks!
