### ISSUE TITLE
dialog noCancelOnEscKey is broken

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-overlay-behavior#50]
_From @borismus on November 2, 2015 22:28_

Regardless of whether or not this boolean value is set to true or false, the dialog can always be canceled with ESC.

_Copied from original issue: Polymer/polymer#2669_

**Comment by arthurevans** [comment]
_From @zoechi on November 3, 2015 8:3_

This should be reported in the GitHub repo of the element. If you look up an element in https://elements.polymer-project.org/ it has a link to the source repo.

**Comment by arthurevans** [comment]
I believe this issue belongs over here.

**Comment by borismus** [comment]
Thanks Arthur!!

**Comment by FabianHoltkoetter** [comment]
@arthurevans https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping 
The second point. Use `no-cancel-on-esc-key` and it works.

**Comment by jwuliger** [comment]
@FabianHoltkoetter Thanks for that tip!
