### ISSUE TITLE
Parsing error in Firefox 42, comment unterminated

### ISSUE THREAD

**Issue by erutan** [PolymerElements/iron-overlay-behavior#59]
More their problem than yours, but if someone else hits it delete lines 41-49 from iron-overlay-behavior.html for the time being.

https://bugzilla.mozilla.org/show_bug.cgi?id=1229966

**Comment by Bodhiz** [comment]
Yep experienced the same issue.

**Comment by erutan** [comment]
@Bodhiz - feel free to chime in on the bugzilla thread.

**Comment by Bodhiz** [comment]
Have been discussed here : 
https://github.com/PolymerElements/iron-overlay-behavior/issues/22
