### ISSUE TITLE
Pass the original event to iron-overlay-canceled event

### ISSUE THREAD

**Issue by tuct** [PolymerElements/iron-overlay-behavior#69]
## Expected 
I can access the original event in iron-overlay-canceled to determine the 

## Actual
Not possible to access the original event

## Long description

I used iron-overlay-behavior triggered by focusing/writing in an input field and wanted to avoid reopening the overlay when i focused the input again after clicking some stuff in the overlay.
(I try to implement a multiselect dropdown where the input is also used to search the options).

Only solution i found that allowed me to still use the close on click outside was to 
add the original source event as detail to the iron-overlay-canceled event
```javascript
(function() {

  Polymer({

    is: 'simple-overlay',

    behaviors: [
      Polymer.IronOverlayBehavior
    ],
    cancel:  function(event) {
      var cancelEvent = this.fire('iron-overlay-canceled', event, {cancelable: true});
      if (cancelEvent.defaultPrevented) {
        return;
      }

      this.opened = false;
      this._setCanceled(true);
    },
    _onCaptureClick:  function(event) {
      if (!this.noCancelOnOutsideClick &&
          this._manager.currentOverlay() === this &&
          Polymer.dom(event).path.indexOf(this) === -1) {
        this.cancel(event);
      }
    }

  });

})();
```
This allowed me to determine if the user clicked the input by adding a on-overlay-canceled function
```
<simple-overlay id="results" class="scrollable" on-iron-overlay-canceled="_checkOverlayCancle">
```
```javascript
      _checkOverlayCancle: function (e){
        if(e.detail != null && 
          e.detail.srcElement != null &&
          e.detail.srcElement.classList.contains("tos-multiselect")){
          e.preventDefault();
          e.stopPropagation();
        }
      }
```

**Comment by valdrinkoshi** [comment]
In the case of `click`, the `event.srcElement` will be the `document.activeElement`, so this should work:
```javascript
      _checkOverlayCancle: function (e){
        if(document.activeElement.classList.contains("tos-multiselect")){
          e.preventDefault();
          e.stopPropagation();
        }
      }

**Comment by valdrinkoshi** [comment]
Here an example http://jsbin.com/migige/1/edit?html,output
Notice I set the `tabindex` and set the css `outline: none` so we don't have the blue border around our div.
Closing this for now, @tuct LMK if that works for you

**Comment by tuct** [comment]
Hi valdrin, 
In chrome on Windows the solution u suggested works, but not on chrome on Android ;(
My fix worked on both  versions.

**Comment by valdrinkoshi** [comment]
true story! If you feel like it, feel free to create a PR with the fix :) (checkout our https://github.com/PolymerElements/iron-overlay-behavior/blob/master/CONTRIBUTING.md to get you started)
