### ISSUE TITLE
using paper-dropdown-menu inside a dialog will close it

### ISSUE THREAD

**Issue by bastienarm** [PolymerElements/iron-overlay-behavior#70]
it seems that there is another problem with the https://github.com/PolymerElements/iron-overlay-behavior/pull/64.

I've made you a JSBin

https://jsbin.com/lapedorogo/edit?html,console,output

I don't know why, but if you use paper-dropdown-menu + paper-menu + paper-item inside a dialog (dialog and paper-dropdown-menu are differents module), when selecting an item in the paper-dropdown-menu, an event will be fired which seems to be "iron-overlay-closed"

Update : no need to select an item, clicking outside to hide the list will have the same effect

**Comment by cdata** [comment]
@bastienarm Thanks for reporting an issue! The event is fired because the dropdowns implement `IronOverlayBehavior` (this is also implemented by dialogs).

Could you clarify in one sentence or so what you think the bug is? The test case is fairly complicated and if there is a bug specific to `IronOverlayBehavior`, it isn't obvious.

Thanks again!

**Comment by bastienarm** [comment]
Thanks for your reply @cdata 

In my opinion, the problem is that, when using a dropdown or a menu inside a dialog, I don't want the dialog to close when selecting an item.

I develop an application in which you have a dashboard with multiple widgets inside. 
You can add a widget to the dashboard when using what I've called a "widget store".
A widget is an indicator based on different options like a period (a day, a week, a month, a year, ...).
This "widget store" is inside a dialog, which is open in overlay. You select your type of widget, and fill the different options. When choosing the period (which is step 2 of 5), you select an item inside a dropdown menu.
But actually, when selecting an item inside the dropdown (or when clicking outside to close the dropdown), both dialog and dropdown receive the "iron-overlay-closed" event.

I can use the event.stopPropagation() to prevent dialog to receive the event, but in my opinion the event should not be the same (I don't know if it's possible or not to be honest) for dialog and dropdown.

(Yeah, I know, it's a little bit more than "one sentence", I'm sorry !)

**Comment by cdata** [comment]
> when using a dropdown or a menu inside a dialog, I don't want the dialog to close when selecting an item

I agree with this. However, I am not convinced that the problem you described is happening under normal conditions.

Can you provide a simpler test case that shows that this happens? Thanks.

**Comment by bastienarm** [comment]
I don't know if it's a "normal condition", but if you look at the JSBin I provided you'll see what I'm doing.

My content inside my dialog is dynamically created and added, and, when closing the dialog the content is removed. (function removeDlg which is called when an iron-overlay-closed event is received)

So, when closing the dropdown, the event is fired, so the removeDlg function is called, which make the contente removed.

I really really don't know if it's a "normal condition" or not to be honest. The fact is that I can stop the propagation of the event and prevent the dialog to close so it's not critical.

**Comment by valdrinkoshi** [comment]
@bastienarm you should check who's the target of the `iron-overlay-closed` event (since you have multiple overlays embedded)
https://jsbin.com/poripe/1/edit?html,console,output
```javascript
removeDlg : function (event) {
  if (event.target === this.$.dialog) {
    console.log("REMOVE DLG")

**Comment by btelles** [comment]
ping @valdrinkoshi  and @cdata 
For what it's worth, I ran into this and it felt a bit betrayed that a dependency way down in paper-dropdown-menu would interfere with another dependency in paper-dialog. It's understandable that those elements will trigger events with the same name, but I think it's unexpected that the paper-dropdown-menu allow the event to keep bubbling. IMHO this violates the "it does what you'd expect" rule, and is pretty difficult to troubleshoot without getting into the deep weeds of these two polymer elements.

**Comment by valdrinkoshi** [comment]
That's fair, `iron-overlay-behavior` should not bubble `iron-overlay-canceled, iron-overlay-opened, iron-overlay-closed` events.

**Comment by valdrinkoshi** [comment]
Hi @btelles, after discussing offline with @notwaldorf, we agree that removing the bubbling of these event would definitely be a breaking change, so we are not going to merge the fix for the time being.
In the future (e.g. `iron-overlay-behavior v2.0`) we might make these events not bubbling.

Fortunately you are not blocked, since you can either check who originated the event, or stop the event propagation (see both methods here http://jsbin.com/tejesa/1/edit?html,output)

**Comment by btelles** [comment]
Ok, that's fair too. Thanks for addressing this @valdrinkoshi
