### ISSUE TITLE
In dynamically created paper-dropdown-menu errored on click outside when opened [Solution]

### ISSUE THREAD

**Issue by jahglow** [PolymerElements/iron-overlay-behavior#76]
Sometimes the `path` wouldn't be on `Polymer.dom(event)` because it returnes a node and event is `CustomeEvent`, thus it would give an error and not close the dropdown on click outside. The following code fixes the issue. please add it to the file.

    _onCaptureClick: function(event) {
      var ev = Polymer.dom(event);
      if (!this.noCancelOnOutsideClick &&
        this._manager.currentOverlay() === this &&
        (
        (ev.path && ev.path.indexOf(this) === -1)
        ||(ev.node
          && ev.node.path
          && ev.node.path.indexOf(this) === -1)
        )) {
        this.cancel();
      }
    },

**Comment by valdrinkoshi** [comment]
`_onCaptureClick` is invoked when `tap` event is triggered on `document`. When can it be a `CustomEvent`? Do you have an example to show this behavior?

**Comment by jahglow** [comment]
I was working on Polymer wrappers for elements on pages that use YUI2/3 basically for everything. There the CustomEvent was overriden by YUI so I had to create an iframe and pass window.CustomEvent from that iframe (otherwise the YUI customEvent was triggering, a nightmare of its kind). I was seeng this thing on paper-dropdown-menu dropdowns - they wouldn't close on click outside - can't set indexOf null

**Comment by valdrinkoshi** [comment]
@jahglow could you please create a jsbin showing the issue? And if you feel like it, feel free to provide a PR with the fix :)

**Comment by jahglow** [comment]
It turns out it was because of this: in my setting YUI2 was overriding
CustomEvent globally, so I had to overwrite it with native CustomEvent from
iFrame, but it turnes out this CustomEvent instanceof Event === false abd
here are the problems, where Polymer would consider an event as a Dom node,
had to alter that in polymer-mini in Polymer.dom declaration and it fized
all this.

ср, 27 янв. 2016, 2:22, Valdrin Koshi <notifications@github.com>:

**Comment by valdrinkoshi** [comment]
Closing this as it seems to have been solved. Feel free to re-open the issue if needed (check https://github.com/PolymerElements/iron-overlay-behavior/blob/master/CONTRIBUTING.md to get you started)
