### ISSUE TITLE
disable horizontal scrollbar inside a paper-dropdown

### ISSUE THREAD

**Issue by bastienarm** [PolymerElements/iron-overlay-behavior#77]
When using a paper-dropwdown-menu a horizontal scrollbar is added, how can i remove it?

Is there any solution to remove it with css?

**Comment by bastienarm** [comment]
seems to be easier that I thought ... my bad.

Adding .dropdown-content class inside my css with overflow-x:hidden solve the problem.
Is it a good solution?

**Comment by valdrinkoshi** [comment]
In which browser does this happen? can you provide an example (jsbin)?

**Comment by valdrinkoshi** [comment]
Closing this since it seems solved. Will re-open if needed.

**Comment by puranjayjain** [comment]
This issue has propped up again in Chrome x64 Version 54.0.2840.99 m

![image](https://cloud.githubusercontent.com/assets/5458094/20798032/67056760-b803-11e6-96a1-9ca8d489fa98.png)
