### ISSUE TITLE
iron overlay behavior - comment syntax bug (very easy fix)

### ISSUE THREAD

**Issue by Bamieh** [PolymerElements/iron-overlay-behavior#81]
iron-overlay-behavior.html (line 19)
the behavior comment starts with /** instead of 
this is causing a parsing issue on firefox, resulting the page to throw and error and ruin the page.

P.S. I caught the error while using polymer iron dropdown, the issue was causing the page to fail on calling the dropdowns to close on page load.

**Comment by valdrinkoshi** [comment]
in line 19 we are inside a `<script>` element, so it is correct to use `/*  */` for comments

**Comment by valdrinkoshi** [comment]
@Bamieh tested the demo page on firefox 42 and 43 (mac os) and didn't see any parsing errors 
http://jsbin.com/niyuru/edit?html,output
Can you provide an example?

**Comment by Bamieh** [comment]
@valdrinkoshi you are correct, i didnt notice we are inside a script tag inside, however i am getting this error on firefox due to the /** instead of /* for some reason.

SyntaxError: unterminated comment
<img width="1068" alt="screen shot 2016-01-06 at 9 27 31 pm" src="https://cloud.githubusercontent.com/assets/6191849/12152274/63383de2-b4bc-11e5-8e5d-29e2812948ae.png">

This is causing my page to crash like this:
<img width="1274" alt="screen shot 2016-01-06 at 9 28 27 pm 1" src="https://cloud.githubusercontent.com/assets/6191849/12152291/7d594590-b4bc-11e5-810e-53412a83bbf5.png">

after removing the comment, the page works fine and all the errors are resolved.

More information:
Name: 	Firefox
Version: 	42.0
User Agent: 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by valdrinkoshi** [comment]
Hi @Bamieh, I cannot reproduce it
![firefox](https://cloud.githubusercontent.com/assets/6173664/12170417/31616318-b4f6-11e5-9387-97a2ad608d75.gif)

#### index.html
```html
<!doctype html>
<!--
html comment here
-->
<html>
<head>
  <base href="http://polygit.org/components/">
  <script src="webcomponentsjs/webcomponents-lite.min.js"></script>
  <link rel="import" href="iron-overlay-behavior/iron-overlay-behavior.html">
</head>
<body>
  <script>
    /** comment here
     * hi
     */
    console.log('index.html');
  </script>
</body>
</html>
```

Can you provide a code snippet to reproduce it?

**Comment by Bamieh** [comment]
I disabled webcomponents in firefox then it worked! hmm..
1. go to, about:config
2. search webcomponents, and setting enabled to false

Seems its not related to this comment particularly but firefox current support for web components in general.
Disabling firefox web components and defaulting to polyfills seems to solve the issue.

Thanks for your time
