### ISSUE TITLE
Backdrop not removed after call to dialog.close() on a modal dialog shortly after open

### ISSUE THREAD

**Issue by akc42** [PolymerElements/iron-overlay-behavior#96]
I am not sure I understand issue #83 and this might be the same, but I suspect not.  I also think it might have been introduced in a fairly recent change - because the code was working fairly recently. However I am not 100% sure of that as I have had to adjust timings of other things to handle a problem with theming. and it is possible that that change meant there are less things for the ajax request (see below) to queue behind.

It is a timing issue in that the dialog box that is opened and closed fairly rapidly. Let me try and explain ...

When I start up my application, I check for the existence of a cookie.  If it doesn't exist I put up a modal dialog box to collect user credentials.  The user clicks on an OK button it doesn't close the dialog box immediately, but rather sends an ajax request to the server to check credentials.  Only if it passes these credentials the server sets the cookie (with an authentication token) and the dialog closes.  This all works fine.

If the cookie exists, I briefly open a modal dialog box with a spinner in it.  I then send an ajax request to the server to ask it to validate the user. Assuming it does, the Ajax response causes me to close the modal dialog box again.

Until recently this all worked fine.  But over the past few days I have been experiencing a complete lock up of the user interface when the second case is true (ie we make this very quick Ajax call which causes me to open and then close the dialog rapidly).  Putting the debugger on things I have been able to see that the overlay is still in place after I have closed the dialog.  From the debugger, it reaches the close function of `iron-overlay-backdrop.html`, which attempts to set the `this.opened` flag to false.  The `_onTransitionend` function is not called.

The flight time of my ajax request seems to be about 6 milliseconds.

I have now added a 200 millisecond delay before closing the dialog and it started working again.

**Comment by valdrinkoshi** [comment]
Hi @akc42, you're right there is this regression on `v1.0.6`. The temporary fix you can use is calling `dialog.backdropElement.complete()` right after you close the dialog (it won't wait for animations to complete).
http://jsbin.com/quxopu/1/edit?html
Also, please provide a jsbin when reporting an issue next time ;)

**Comment by akc42** [comment]
I did a bower update, and your fix has stopped working.  I have had to revert to the 200ms delay to make things work again

I presume, unless I do something special, I am just tracking your releases - which you haven't made in the last few days, so I have no idea of the reasons for it stopping, other than I have been streamlining things so they run a lot faster.

**Comment by valdrinkoshi** [comment]
I haven't released a new version yet, but on master this is working http://jsbin.com/tihiwe/1/edit?html,output
