### ISSUE TITLE
iron-overlay-opened should be called after iron-resize

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-overlay-behavior#97]
Currently, `iron-resize` gets called after `iron-overlay-opened` http://jsbin.com/xeyeqef/1/edit?html,console,output
Shouldn't `iron-overlay-opened` be called only after `iron-resize` instead?

**Comment by tuct** [comment]
+1, otherwise I might run into problems if the stuff I do in `iron-overlay-opened` relies on `iron-resize`
