### ISSUE TITLE
use requestAnimationFrame

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-overlay-behavior#99]
It would improve performance to delay `_onIronResize` via `requestAnimationFrame`. e.g.
```javascript
    
    // properties...
    _boundOnIronResize: {
        type: Function,
        value: function() {
          return requestAnimationFrame(this._onIronResize.bind(this));
        }
      }
    //...
    listeners: {
      'iron-resize': '_boundOnIronResize'
    },
    //...
    _onIronResize: function(){
       //can be overridden
    }
```
Same for `_renderOpened/_renderClosed`

**Comment by cdata** [comment]
Do you think we should do this for all `iron-resize` events, perhaps?

**Comment by valdrinkoshi** [comment]
@cdata yes, at each `iron-resize` the overlay should `requestAnimationFrame` in order to perform `_onIronResize`. 
This could be implemented in such a way that `iron-overlay-behavior` exposes only 1 protected method to be overridden (`_onIronResize`). This would be invoked in another private method `__ _boundOnIronResize` (which requests the animation frame). This way everyone who extends `iron-overlay-behavior` should benefit in animations performance and not have to worry about requesting animation frames.
